### ISSUE TITLE
Cloned Application Users with null passwordLastSet Causes Failure

### ISSUE THREAD

**Issue by stokes776** [Losant/losant-templates#1]
When an Application is Cloned, and has Experience users, those users are moved into the new application in Losant.

These users in the new application, seem to lack a passwordLastSet value on their Experience User attributes.

This causes the customNode to report a failure when running 'Password not reset yet?' block.
Could it possibly coalesce (or be changed) to instead compare to lastLogin or lastUpdated? I do not know if those values are present on a cloned application User.

![image](https://user-images.githubusercontent.com/50416033/98416915-a3ed4400-2045-11eb-8ae2-5cb80a08d7da.png)

![image](https://user-images.githubusercontent.com/50416033/98416926-a94a8e80-2045-11eb-8d23-9b59814ce5d4.png)

![image](https://user-images.githubusercontent.com/50416033/98417299-502f2a80-2046-11eb-98fe-f76304fde344.png)

Here are the user fields that seem to be available from a brand new cloned application, against an experience user that has never logged in:

![image](https://user-images.githubusercontent.com/50416033/98417352-650bbe00-2046-11eb-9441-ea37c94c8527.png)

**Comment by cephirothdy2j** [comment]
Thanks for reporting the issue. I see what you're talking about and am working on a fix right now; I hope to have the updated template published by day's end.

If you wish to fix it now without having to re-import the Forgot Password template, the fix is quite simple:

1. Find the "Verify Reset Token" custom node that was imported with the Forgot Password template.
2. Find the last Conditional Node in the custom node, which is labeled "Password not reset yet?"
3. Change the expression to: `{{formatDate (defaultTo working.user.passwordLastUpdated 0) 'X'}} < {{working.decoded.iat}}`

This will, in the absence of the "passwordLastUpdated" property, default the timestamp to 0 (Jan 1 1970), which will allow the token to be recognized as valid. In all other cases, the "passwordLastUpdated" property should be set on the experience user.

<img width="766" alt="Screen Shot 2020-11-16 at 12 52 00 PM" src="https://user-images.githubusercontent.com/881769/99289106-87ea5f00-280a-11eb-8586-285d91716684.png">
